# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ps9s < Formula
  desc "AWS Parameter Store TUI"
  homepage "https://github.com/caseycs/ps9s"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caseycs/ps9s/releases/download/v0.1.4/ps9s_0.1.4_darwin_amd64.tar.gz"
      sha256 "e628c1f7d84c04c3dddfe1430a43adfbce47d820e6c3ff94777afaebf329e3cf"

      define_method(:install) do
        bin.install "ps9s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caseycs/ps9s/releases/download/v0.1.4/ps9s_0.1.4_darwin_arm64.tar.gz"
      sha256 "794d90c10df49a7b916a49822777fa2a40a35b4dd67502a2e0d6cf302416f006"

      define_method(:install) do
        bin.install "ps9s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caseycs/ps9s/releases/download/v0.1.4/ps9s_0.1.4_linux_amd64.tar.gz"
      sha256 "8fe5f2659fd414fd3e05983f9a6009f7264fce995b8ff4ea927fa802ef49a632"
      define_method(:install) do
        bin.install "ps9s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caseycs/ps9s/releases/download/v0.1.4/ps9s_0.1.4_linux_arm64.tar.gz"
      sha256 "dc65332d09ec9c5f28fcec06d6e044cf0f43d1f308baa4438e8ca372b2e3d45e"
      define_method(:install) do
        bin.install "ps9s"
      end
    end
  end

  test do
    system "#{bin}/ps9s", "--help"
  end
end
