# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ps9s < Formula
  desc "AWS Parameter Store TUI"
  homepage "https://github.com/caseycs/ps9s"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caseycs/ps9s/releases/download/v0.1.3/ps9s_0.1.3_darwin_amd64.tar.gz"
      sha256 "454f1eb9f63cc978d6faa665da2fbbf8aefb7d91fa1cdb0ca8ab8e916cc33abc"

      def install
        bin.install "ps9s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caseycs/ps9s/releases/download/v0.1.3/ps9s_0.1.3_darwin_arm64.tar.gz"
      sha256 "bee97e8d13e27ea0c095852a624a7f496a44c618de471a6b5a1688444720331b"

      def install
        bin.install "ps9s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caseycs/ps9s/releases/download/v0.1.3/ps9s_0.1.3_linux_amd64.tar.gz"
      sha256 "d660305c5a0ffd768b756dc56998f08d9d096f83b83cbdccda56eb77b6cdc1c4"
      def install
        bin.install "ps9s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caseycs/ps9s/releases/download/v0.1.3/ps9s_0.1.3_linux_arm64.tar.gz"
      sha256 "5cad16d18f351bf218f22cac1c245abf8afcfa90dff234928d1722bf66a429ff"
      def install
        bin.install "ps9s"
      end
    end
  end

  test do
    system "#{bin}/ps9s", "--help"
  end
end
