# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ps9s < Formula
  desc "AWS Parameter Store TUI"
  homepage "https://github.com/caseycs/ps9s"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caseycs/ps9s/releases/download/v0.1.2/ps9s_0.1.2_darwin_amd64.tar.gz"
      sha256 "438a5ba1fa72dceecc791094c9f3ff8fb85615e601f6f794234f7ceb5156eeb8"

      def install
        bin.install "ps9s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caseycs/ps9s/releases/download/v0.1.2/ps9s_0.1.2_darwin_arm64.tar.gz"
      sha256 "1cf34f6deacb7daa9aa652ebc0a61dee8c8b4f153c9bac4888d0bf2c7cf7be3e"

      def install
        bin.install "ps9s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caseycs/ps9s/releases/download/v0.1.2/ps9s_0.1.2_linux_amd64.tar.gz"
      sha256 "1c2bf76b81b4369f69dab0d5a28f383c1221d1035f65d392260bce059476c037"
      def install
        bin.install "ps9s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caseycs/ps9s/releases/download/v0.1.2/ps9s_0.1.2_linux_arm64.tar.gz"
      sha256 "38840ea9df3d6d1d8af03d7472b69e7e54d8117c7e78c4317ace9ad3a750d35c"
      def install
        bin.install "ps9s"
      end
    end
  end

  test do
    system "#{bin}/ps9s", "--help"
  end
end
